import type { Metadata, Viewport } from 'next';

export const viewport: Viewport = {
	themeColor: '#000',
	width: 'device-width',
	initialScale: 1,
};

export const metadata: Metadata = {
	title: 'A public todo app',
	description: 'Generated by create next app, using app routing approach.',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
