import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
	title: 'Another page to say hello to user',
	description: 'Generated by create next app, using app routing approach.',
};

export default function HelloPage() {
	const message = 'Hello, world!';

	return (
		<section>
			<h1>Message coming from the server</h1>
			<p>{message}</p>
			<Link href="/">Go back home</Link>
		</section>
	);
}
